spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile:
        - local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: localhost
---
spring:
  config:
    activate:
      on-profile:
        - prod

  data:
    mongodb:
      host: prod
      port: 27017
      database: prod

